/**
 * Data Model
 * Business logic for calculations and data structure
 */

const Model = {
    /**
     * Create a new empty invoice object structure
     */
    createEmptyInvoice() {
        return {
            id: '', // Will be generated by Storage on save if empty
            createdDate: new Date().toISOString().split('T')[0],
            dueDate: new Date().toISOString().split('T')[0],
            status: 'draft',
            client: {
                name: '',
                email: '',
                address: ''
            },
            items: [],
            subtotal: 0,
            taxRate: 0,
            taxAmount: 0,
            total: 0,
            notes: ''
        };
    },

    /**
     * Create a new line item
     */
    createLineItem() {
        return {
            id: crypto.randomUUID(),
            description: '',
            quantity: 1,
            rate: 0,
            amount: 0
        };
    },

    /**
     * Calculate totals for an invoice
     * @param {Object} invoice
     * @returns {Object} Updated invoice with calculations
     */
    calculateInvoice(invoice) {
        // Calculate item amounts
        invoice.items.forEach(item => {
            item.amount = (item.quantity || 0) * (item.rate || 0);
        });

        // Calculate subtotal
        invoice.subtotal = invoice.items.reduce((sum, item) => sum + item.amount, 0);

        // Calculate tax
        invoice.taxAmount = invoice.subtotal * ((invoice.taxRate || 0) / 100);

        // Calculate total
        invoice.total = invoice.subtotal + invoice.taxAmount;

        return invoice;
    },

    /**
     * Format currency
     * @param {number} amount
     * @param {string} currency
     * @returns {string}
     */
    formatCurrency(amount, currency = 'USD') {
        return new Intl.NumberFormat('en-US', {
            style: 'currency',
            currency: currency
        }).format(amount);
    },
    
    /**
     * Format date
     * @param {string} dateString
     * @returns {string}
     */
    formatDate(dateString) {
        if (!dateString) return '';
        // Handle ISO date string (yyyy-mm-dd) to avoid timezone issues by treating as UTC or local consistently
        // For display simplicity we can just parse parts if needed, but Date object usually works if browser locale is set
        // Using simple split to avoid timezone shifts on pure dates
        const parts = dateString.split('-');
        if (parts.length === 3) {
            const date = new Date(parts[0], parts[1] - 1, parts[2]);
            return new Intl.DateTimeFormat('en-US', {
                year: 'numeric', 
                month: 'short', 
                day: 'numeric'
            }).format(date);
        }
        
        // Fallback
        return dateString;
    }
};